on_internal_error: add overload taking an std::exception_ptr
Often, when calling on_internal_error, an exception object is handy,
because for example on_internal_error() is called from a catch clause.
Add a convenience overload for these cases. This also allows for
customizing the type of the exception to-be-thrown when
--abort-on-internal-error is not set.